name: Deploy to Azure Web App

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: proyecto-informatico
  AZURE_WEBAPP_PACKAGE_PATH: './dist'
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
        
    - name: Check if dist directory exists
      run: if [ -d "./dist" ]; then echo "dist exists"; else echo "dist does not exist"; fi

    - name: List files in root directory
      run: ls -la

    - name: List files in dist directory
      run: ls -la ./dist

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: List files in downloaded artifact
      run: ls -la /node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: /node-app
