name: CI

on:
  pull_request:
    branches: [ main ]
env:
  AZURE_WEBAPP_NAME: proyecto-informatico
  AZURE_WEBAPP_PACKAGE_PATH: "./build"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

    - name: Run tests
      run: npm test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.5
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.organization=<your_organization_key>
          -Dsonar.projectKey=<your_project_key>
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"

